-- Create Table
CREATE TABLE TBL_USER (
    USER_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Constraint
ALTER TABLE TBL_USER ADD CONSTRAINT constraint_user_role CHECK (ROLE IN ('CUSTOMER', 'ADMIN'));

-- Unique
CREATE UNIQUE INDEX unique_user_email ON TBL_USER (EMAIL);

-- Trigger
CREATE OR REPLACE TRIGGER trigger_user_updated_at
BEFORE UPDATE ON TBL_USER
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSDATE;
END;
/