-- Create Table
CREATE TABLE TBL_DISPATCH (
    DISPATCH_ID      NUMBER PRIMARY KEY,
    ORDER_ID         VARCHAR2(50) NOT NULL,
    WAREHOUSE_NAME   VARCHAR2(100) NOT NULL,
    DISPATCH_DATE    DATE NOT NULL,
    DISPATCHER       VARCHAR2(50) NOT NULL,
    SOURCE_TYPE      VARCHAR2(20) DEFAULT 'MANUAL' NOT NULL,
    UPDATED_BY       VARCHAR2(50),
    UPDATED_AT       TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CREATED_AT       TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Contraint
ALTER TABLE TBL_DISPATCH
ADD CONSTRAINT fk_dispatch_order FOREIGN KEY (ORDER_ID)
REFERENCES TBL_ORDER (ORDER_ID);

ALTER TABLE TBL_DISPATCH
ADD CONSTRAINT constraint_dispatch_source CHECK (
    SOURCE_TYPE IN ('MANUAL', 'RPA')
);

-- Trigger
CREATE OR REPLACE TRIGGER trg_dispatch_updated_at
BEFORE UPDATE ON TBL_DISPATCH
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSDATE;
END;
/

-- Sequence
CREATE SEQUENCE SEQ_DISPATCH_ID START WITH 1 INCREMENT BY 1;