-- Create Table
CREATE TABLE TBL_SHIPMENT (
    SHIPMENT_ID        NUMBER PRIMARY KEY,
    ORDER_ID           VARCHAR2(50) NOT NULL,
    CARRIER_NAME       VARCHAR2(100),
    TRACKING_NUMBER    VARCHAR2(50),
    SHIPPED_AT         TIMESTAMP,
    ARRIVAL_ESTIMATE   DATE,
    SHIPMENT_STATUS    VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    SOURCE_TYPE        VARCHAR2(20) DEFAULT 'MANUAL' NOT NULL,
    UPDATED_BY         VARCHAR2(50),
    UPDATED_AT         TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CREATED_AT         TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Constraint
ALTER TABLE TBL_SHIPMENT
ADD CONSTRAINT fk_shipment_order
FOREIGN KEY (ORDER_ID)
REFERENCES TBL_ORDER (ORDER_ID);

ALTER TABLE TBL_SHIPMENT
ADD CONSTRAINT constraint_shipment_status CHECK (
    SHIPMENT_STATUS IN ('READY', 'IN_TRANSIT', 'DELIVERED')
);

ALTER TABLE TB_SHIPMENT
ADD CONSTRAINT constraint_shipment_source CHECK (
    SOURCE_TYPE IN ('MANUAL', 'RPA')
);

-- Trigger
CREATE OR REPLACE TRIGGER trg_shipment_updated_at
BEFORE UPDATE ON TB_SHIPMENT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;
/

-- Sequence
CREATE SEQUENCE SEQ_SHIPMENT_ID
START WITH 1
INCREMENT BY 1
NOCACHE;