-------------------------------------------------
-- 1. TBL_ORDER: 오더 도메인
-------------------------------------------------
-- Create Table
CREATE TABLE TBL_ORDER (
    ORDER_ID    VARCHAR2(50) PRIMARY KEY,
    USER_ID     VARCHAR2(50) NOT NULL,
    TITLE       VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    STATUS      VARCHAR2(20) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Constraint
ALTER TABLE TBL_ORDER
ADD CONSTRAINT fk_order_user FOREIGN KEY (USER_ID)
REFERENCES TBL_USER (USER_ID);

ALTER TABLE TBL_ORDER
ADD CONSTRAINT constraint_order_status CHECK (
    STATUS IN ('READY', 'PICKUP', 'DISPATCHED', 'DELIVERED', 'COMPLETED', 'DELETED')
);

-- Trigger
CREATE OR REPLACE TRIGGER trg_order_updated_at
BEFORE UPDATE ON TBL_ORDER
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSDATE;
END;
/

-- Sequence
CREATE SEQUENCE SEQ_ORDER_ID START WITH 1 INCREMENT BY 1;

-------------------------------------------------
-- 2. TBL_ITEM: 아이템 도메인
-------------------------------------------------
-- Create Table
CREATE TABLE TBL_ITEM (
    ITEM_ID   VARCHAR2(50) PRIMARY KEY,
    ORDER_ID  VARCHAR2(50) NOT NULL,
    NAME      VARCHAR2(200) NOT NULL,
    QUANTITY  NUMBER(10) NOT NULL,
    UNIT      VARCHAR2(10) NOT NULL,
    WEIGHT    NUMBER(10, 2),
    HS_CODE   VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Constraint
ALTER TABLE TBL_ITEM
ADD CONSTRAINT fk_item_order FOREIGN KEY (ORDER_ID)
REFERENCES TBL_ORDER (ORDER_ID);

ALTER TABLE TBL_ITEM
ADD CONSTRAINT constraint_item_unit CHECK (UNIT IN ('EA', 'KG'));

-- Trigger
CREATE OR REPLACE TRIGGER trg_item_updated_at
BEFORE UPDATE ON TBL_ITEM
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSDATE;
END;
/

-- Sequence
CREATE SEQUENCE SEQ_ITEM_ID START WITH 1 INCREMENT BY 1;

-------------------------------------------------
-- 3. TBL_ORDER_STATUS_HISTORY: 오더 상태 히스토리 도메인
-------------------------------------------------
-- Create Table
CREATE TABLE TBL_ORDER_STATUS_HISTORY (
    HISTORY_ID   NUMBER PRIMARY KEY,
    ORDER_ID    VARCHAR2(50) NOT NULL,
    STATUS      VARCHAR2(20) NOT NULL,
    UPDATED_BY  VARCHAR2(50) NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Constraint
ALTER TABLE TBL_ORDER_STATUS_HISTORY
ADD CONSTRAINT fk_history_order FOREIGN KEY (ORDER_ID)
REFERENCES TBL_ORDER (ORDER_ID);

ALTER TABLE TBL_ORDER_STATUS_HISTORY
ADD CONSTRAINT constraint_history_status CHECK (
    STATUS IN ('READY', 'PICKUP', 'DISPATCHED', 'DELIVERED', 'COMPLETED', 'DELETED')
);

-- Sequence
CREATE SEQUENCE SEQ_HISTORY_ID START WITH 1 INCREMENT BY 1;